### ISSUE TITLE
ID_ZONE in RSU table ?

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#193]
I wonder when it is the best solution to add the ID_ZONE in the RSU table.
Two issues :

- it is quite complicated to add it at the begining of the geoclimate processing chain since we would act differently for OSM or BDTopo.
- It seems that it is only useful to feed a general table that could gather the results for several cities ?

Thus in my opinion the ID_ZONE must be integrated in the RSU table only at the feeding step (in the "loop") since we will process city by city.

**Comment by j3r3m1** [comment]
After a chat with @gpetit, the easiest solution would be (for both the user and our point of view) to add the ID_ZONE information to the RSU table. I do that

**Comment by ebocher** [comment]
Do not do that. 
The id_zone must be added during loop only for the BDTopo process

**Comment by gpetit** [comment]
? ID_ZONE is supposed to be present in resulting table even on OSM. If not, how do you know where you executed the chain ?

**Comment by ebocher** [comment]
There is no id_zone in OSM because you query the data according a place name. The place name is whatever : a country name, a urban block, a french urban unit... 
OSM results will be not merged into a unique table.

**Comment by gpetit** [comment]
I know but if i'm not wrong (@j3r3m1 told me), we are currently already storing something in the ID_ZONE field (in the ZONE table). This value is the text used to search the place. So it can be "Vannes", "Nantes metropole", ... and it may be helpul to keep it.

If you remove it for OSM, it means that the Geoclimate chain is not generic since we make modifications depending on the input dataset.

`OSM results will be not merged into a unique table.` --> according to you. But why shouldn't users be allowed to do so? 
How will you proceed if you want to process a lot of zones (example: square grid that each have an ID) (as we will do for the BD Topo)?

**Comment by gpetit** [comment]
Ok, so the boss won ;-)
I will remove `ID_ZONE` from RSU, Block and Building tables.
... and I will keep this information only in "our" BD Topo process

**Comment by ebocher** [comment]
nope. We're both okay. ;-)
It's just the use with OSM and BDTopo that's different

**Comment by j3r3m1** [comment]
very well then I have nothin to change, we will feed the general table with the id_zone only using the loop.

**Comment by gpetit** [comment]
Yes, I will add the ID_ZONE (code INSEE for BD Topo) in the 3 tables on the fly
