### ISSUE TITLE
Parking areas

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#205]
Extract amenity=parking and transform it to polygon layer to improve impervious density

**Comment by gpetit** [comment]
Just one remark : I really understand the need since it will give an interesting information. But depending on the input dataset this information may be stored in another input layer than roads.
Moreover, this kind of objects is supposed to be a POLYGON, while ROAD layer has only LINESTRINGS. So in a conceptual point of view we may have a problem.

For example, concerning BD Topo, parkings are stored in a "SURFACE_ROUTE" layer ([see](http://professionnels.ign.fr/doc/DC-BDTOPO-2-2.pdf#%5B%7B%22num%22%3A104%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C785%2C0%5D)).

@j3r3m1 @ELSW56

**Comment by ELSW56** [comment]
@j3r3m1 

PR #210 should bring you what you need.
A new table Impervious is built using OSM data. Its content has been built taking into account the following elements :

- Parking : amenity in {parking, bicycle_parking, car_sharing, parking_space}
- Railway platforms : railway = platform
- squares : highway in {residential, pedestrian} and area = yes
- industrial, commercial and retail areas : landuse in {industrial, commercial, landuse}

Once the raw data is collected, the objects have been inserted in the final table only if :

- surface != grass
- parking != underground

Let me know if this meets your needs or if you see anything that needs improvement.

**Comment by j3r3m1** [comment]
It seems OK for me. For industrial, commercial and retail, you mean landuse in {industrial, commercial, **retail**} I suppose ?

**Comment by ELSW56** [comment]
Yes indeed ! :wink:

**Comment by gpetit** [comment]
I guess we can close this issue ?

**Comment by ebocher** [comment]
We must check if the osm keys values is well setted

**Comment by ebocher** [comment]
Fixed
