### ISSUE TITLE
First results for the whole chain : OSM with estimated height on Vannes

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#448]
**OSM Workflow configuration file :** 
```json
"parameters":
                        ["distance" : 0,
                         "indicatorUse": ["LCZ", "URBAN_TYPOLOGY"],
                         "svfSimplified": false,
                         "prefixName": "",
                         "mapOfWeights":
                                 ["sky_view_factor"                : 4,
                                  "aspect_ratio"                   : 3,
                                  "building_surface_fraction"      : 8,
                                  "impervious_surface_fraction"    : 0,
                                  "pervious_surface_fraction"      : 0,
                                  "height_of_roughness_elements"   : 6,
                                  "terrain_roughness_length"       : 0.5],
                         "hLevMin": 3,
                         "hLevMax": 15,
                         "hThresholdLev2": 10,
                         "estimateHeight":false
                        ]
```
**Results** 
Note : go to http://mapuce.orbisgis.org/ to compare with Mapuce results.

Urban typo with area
![osm_urban_typo_area](https://user-images.githubusercontent.com/1820572/96684453-dfb4b800-137b-11eb-8569-bacf8b67e16d.png)

Urban typo with floor area
![osm_urban_typo_flow_area](https://user-images.githubusercontent.com/1820572/96684480-f0fdc480-137b-11eb-98bd-4f7cf6234183.png)

Legend
![urban_typo_legend](https://user-images.githubusercontent.com/1820572/96688264-44264600-1381-11eb-8d25-184bc781aac0.png)

LCZ
![osm_lcz_h_estimated](https://user-images.githubusercontent.com/1820572/96685449-67e78d00-137d-11eb-9dce-2bbc631188df.png)

Legend
![lcz_legend](https://user-images.githubusercontent.com/1820572/96688290-4d171780-1381-11eb-9c9f-be304c2ad835.png)

**Comment by j3r3m1** [comment]
The problem is larger on Urban typo than the LCZ. Three assumptions to investigate in three different PR:
- the build_type of half of the "bâtiment d'activité" in the training data has been set to residential. We propose to remove these buildings from the training data
- the number of building in the OSM training data is larger than the BDTopo one (27000 vs 20000). This is due to the spatial join and the fact that all intersected buildings in OSM are conserved. We may conserve only buildings intersected more than 90% of training data buildings.
- we may modify the RF parameters in order to optimize the training which has worse results than in Python

**Comment by ebocher** [comment]
Update with https://github.com/orbisgis/geoclimate/pull/456

Urban typo with area

![osm_urban_typo_area_pr_456](https://user-images.githubusercontent.com/1820572/96982618-378c2400-1520-11eb-9c18-93c034f03616.png)

Urban typo with floor area

![osm_urban_typo_floor_area_pr_456](https://user-images.githubusercontent.com/1820572/96982669-3a871480-1520-11eb-80dd-8d2ae3973a7b.png)

**Comment by ebocher** [comment]
So brilliant ! with the last fixe for LCZ

![osm_lcz_vannes_estimated](https://user-images.githubusercontent.com/1820572/98700038-0b71ff00-2378-11eb-8f5f-177d224e6a04.png)

done with @j3r3m1
