### ISSUE TITLE
Color in the terminal too much dark

### ISSUE THREAD

**Issue by j3r3m1** [orbisgis/geoclimate#537]
In the last version of the command line Geoclimate.jar, I do not see the text which is displayed in the terminal which is supposed to inform me what is computing.
![image](https://user-images.githubusercontent.com/13120405/107240832-a5565000-6a2a-11eb-8e5a-56f33353c5f1.png)

@SPalominos any idea ?

**Comment by ernlt** [comment]
You can change the background color of the terminal to white, and you will be able to read the output messages.

**Comment by j3r3m1** [comment]
Yes I see your point but:
- it does not work,
- I did not get such issue until recently so I wonder whether it was due to a recent change in Geoclimate

**Comment by SPalominos** [comment]
It's due to the recent change on the logger engine (we moved from `slf4j` to `log4j2`) and we now have a [configuration file](https://github.com/orbisgis/geoclimate/blob/master/geoindicators/src/main/resources/log4j2.xml) which sets the colors. The colormap is written for "white mode", that explain why the `info` messages are dark.

I'm looking for a solution

**Comment by ebocher** [comment]
Fixed by @SPalominos 
https://github.com/orbisgis/geoclimate/pull/539

**Comment by j3r3m1** [comment]
Tack !
