### ISSUE TITLE
IRIS_GE table as input never used 

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#572]
The IRIS_GE is used to find a list of INSEE codes (unique French identifier) and compute a geometry area based on the union of all IRIS geoms.

I think we should remove this and work either with a list of zones like OSM or with the commun table provided by  bdtopo db

@j3r3m1

**Comment by j3r3m1** [comment]
Ideally if we may have the least differences between OSM and BDTopo it is easier to understand for the user and to maintain for us. Is it possible to easily cast the type entered by the user and go for a commune name if it is a string or a commune insee code if iwe can cast it as a number ? Because I would first go for list of commune names but it could be uncomfortable for some commune names with specific characters so leaving the chance to use insee code would be nice.

**Comment by ebocher** [comment]
Good catch. This is what I have in mind. We can use the name, the insee code and perhaps in the future a geometry envelope.

**Comment by gpetit** [comment]
Hi guys,
Just to remind you that initially the `IRIS_GE` has been choosed because we wanted to be able to process the indicators and classification at the IRIS scale. At this time, the `IRIS_GE` db was the only one with geometries that were consitant with BD Topo ones.
If no need to process at the IRIS scale, yes this table is useless

**Comment by j3r3m1** [comment]
You are right. However currently it is not a generic table so it will be removed. In the future several ways could be used to consider the relations with socio-economic data:
- using it "outside Geoclimate" but using Geoclimate functions: the results at the TSU scale may be aggregated at the socio-economic unit (then for example relations with LCZ would make sense since they would come from a bottom-up approach)
- adding it as a generic table:
    - which would be used in the Topographical Spatial Unit (TSU) creation: in this case the problem is that it will not be topographical anymore (we can consider that commune boundaries are more or less)
    - which will be used directly as RSU: then some informations such as the LCZ would probably have less sense since it will not come from a "bottom-up" approach anymore

**Comment by ebocher** [comment]
IRIS-GE removed and replaced by COMMUNE layer
