### ISSUE TITLE
Different results with bbox and geoname

### ISSUE THREAD

**Issue by 4estone** [orbisgis/geoclimate#611]
Hello,
I process OSM data on same area with 2 different params:

- "strasbourg"
- [48.53272340942283,7.607115013436108,48.627941932334664,7.750620152813616]
And result is slighly different. I understand that it can occure at the edge of bounding box but not in the center. 
Could you give me some explaination?
Thanks

**Comment by j3r3m1** [comment]
Hi,
Not sure I really got your problem. As I understood is that you performed two calculations using OSM data:
- using a placename : Strasbourg
- using a bounding box encompassing Strasbourg ?
And then you get different results near the center of the bounding box ?
Then few more informations would make your question clearer:
- is the center of your bounding box is also the center of Strasbourg or near an edge of Strasbourg ?
- what are you comparing ? LCZ ?
- Can you share one (or several) maps illustrating the differences.

**Comment by 4estone** [comment]
More informations:
Yes I'm comparing LCZ.
The bounding box center is not the center of Strasbourg (I've created a grid to cover a wide area, so edge of bounding box doesn't feet administrative boundaries.
Two  screenshots:
![Capture1](https://user-images.githubusercontent.com/36297033/125918047-ff756329-857e-4d01-acfb-fdf256991ab5.PNG)
![Capture2](https://user-images.githubusercontent.com/36297033/125918055-4714ff53-8724-4604-8c91-3801b25bf58d.PNG)

**Comment by j3r3m1** [comment]
OK I see plenty of differences. Thank you for reporting, we will have a test on a smaller area, it may come from the way we recovering the data from one method compared to the other. But it is not expected indeed it is a bug.

**Comment by j3r3m1** [comment]
OK I got the problem. This is actually not what we can call a bug but an unexpected result... The RSU you are pointing are actually really close to several LCZ types. What makes them being different between two calculations is not due to the bounding box or the placename but due to the SVF method calculation.

As you probably know, the SVF is used for the LCZ classification. There are currently two ways of calculating the SVF:
- standard way: a given set of points are randomly chosen within the free spaces of a given RSU (a given density of point / free area used for the calculation is based on Bernard et al. (2018) results[https://www.mdpi.com/2225-1154/6/3/60]. The SVF is calculated for each point and then averaged at the RSU scale. This is generally "quite" accurate (in 50% of the cases, SVF is within 0.01 error) but there are two shortcomings:
    - the calculation time could be quite long, 
    - the points are randomly chosen, thus leading to differences in the results between two calculations...
- a simplified way: in the same article as previously pointed, we have identified a linear relationship between the SVF and the "facade density". Thus we used this linear relationship to calculate the SVF based on the "facade density" calculation. The major shortcoming is the lack of accuracy (95% of the time SVF has less than 0.2 error).

The differences between the two methods are illustrated Figure 14 of the article. 

For the RSU being at the border of one LCZ type, the slight difference of SVF value may lead to a different classification when recomputed. To identify RSU where you may experience such problem, I recommend mapping the LCZ_UNIQUENESS_VALUE. Lower the value, less unique the LCZ type... You will probably have a value lower than 0.15 for most of the RSU identified as having a different LCZ type between two calculations. For those LCZ, you may consider they do not have a single LCZ type...

However, to avoid this strange behavior (having different results for a same calculation...), we may think about several solutions:
- using a regular grid of points within each RSU, the distance between two points being related to the building density (higher the density, lower the distance). The advantage is that there is no random anymore so consistent results between two simulations. The shortcoming is that we may have lower number of points for some RSU depending on building distribution, thus leading to unexpected error.
- keeping the random distribution method leaving to the user the opportunity to choose the density of points (higher the density, lower the difference between two simulations, lower the chance to get different results between two simulations). The advantage is that we can have "very accurate" (just remember that trees and slopes are not considered) SVF value for specific use of this parameter. The shortcoming is that we still can have differences between two calculations.
- using the estimated SVF to True: the shortcoming is that the accuracy is lower, the advantage is that there is no differences anymore between two calculations...

What do you think ?
@ebocher @franetibe @ELSW56

**Comment by ebocher** [comment]
@j3r3m1 
I will be OoO until end of August so I will not be able to check your proposals  in the coming days.
Cheers

**Comment by ebocher** [comment]
Because using the estimated SVF to True has a limited impact on the classifications LCZ and UTRF I am in favor of this solution.
Concretely this means that by default GeoClimate will calculate a simplified SVF.
I propose also to update the doc in order to explain this choice.

**Comment by ebocher** [comment]
Fixed with the estimated SVF to True as default value
