### ISSUE TITLE
compilation error:  GroovyRuntimeException

### ISSUE THREAD

**Issue by diouck** [orbisgis/geoclimate#639]
hello Have you ever encountered this error and how could you solve it. I just ran this command with Grooovy

@GrabResolver(name='orbisgis', root='https://nexus.orbisgis.org/repository/orbisgis/')
@Grab(group='org.orbisgis.geoclimate', module='geoclimate', version='1.0.0-SNAPSHOT')

import org.orbisgis.geoclimate.Geoclimate

def process = Geoclimate.OSM.workflow
process.execute(configurationFile:'C:\\Geoclimate\\my_first_config_file_osm.json')

Exception thrown
groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-sql is loaded in version 3.0.9 and you are trying to load version 3.0.7

Do you have to run it with version 3.0.7?
By trying this version it seems to work

Best

**Comment by j3r3m1** [comment]
Hi,
Yes you have identified the problem. Only the 3.0.7 version can be used right now (see #575).

You can now find a solution to your problem in the FAQ: https://github.com/orbisgis/geoclimate/wiki/Frequently-Asked-Questions#groovy-version-issue

I have added it right now since you are not the first to meet this error and to wonder. Thanks for reporting !
