### ISSUE TITLE
Building passiv volume

### ISSUE THREAD

**Issue by gpetit** [orbisgis/geoclimate#8]
Seems there is an error in the definition of the building passiv volume. Indeed, the formula must take into account only the free facades (party walls are not considered)

... and in the code here, it's not the case
https://github.com/orbisgis/geoclimate/blob/c5c9281cd9f49936732df99ba1e43c36e9bea105/geoindicators/src/main/groovy/org/orbisgis/BuildingIndicators.groovy#L68

Not sure, but for me this indicator is so complex, we should extract it into a specific script.

@j3r3m1 @ebocher

**Comment by ebocher** [comment]
building_passive_volume_ratio must be computed with the following method describe in G. P script documentation.
The code location sounds good for me.

**Comment by j3r3m1** [comment]
@gpetit You are right, my script was slightly simplified... But totally wrong ! Regarding the complexity of the SQL queries, it seems that a specific script would be appropriate.
However, the calculation in G P is not completely right even, since it consider that an intersection between two buildings cover the wall up to the building top. In fact, a free facade could be observed on the upper part of the building if its neighbor is low.
I will remove this indicator from the existing code

**Comment by j3r3m1** [comment]
In the GP report, the code is based on a epsilon value defined as a tolerance distance. Below this distance, the buildings are merged. In my opinion, this step should not be made in the building passive volume calculation but rather in the pre-process stage because it means that the geometries are slightly modified. The calculation of the other indicators should then be used using these merged geometries.

**Comment by gpetit** [comment]
Hi @j3r3m1 
* concerning the free facade, yes you are right. Let say, it was a simplification of an already quite complex indicator ;-) Nice if we can complexify it
* the epsilon value has been added only to avoid some weird results and errors, due to precision bugs.
* the "merged" geometry is only used in this indicator... and the difference with the reality is more or less equal to 0 since epsilon is "nothing" (5 millimeter). So I don't see your point. Why it is a problem ?

**Comment by ebocher** [comment]
Postoned

**Comment by gpetit** [comment]
Any news ?

**Comment by ebocher** [comment]
Keep this issue opened
