### ISSUE TITLE
New attribute "TYPO_SECOND" in RSU UTRF output files (rsu_utrf_floor_area, rsu_utrf_area)?

### ISSUE THREAD

**Issue by sfaraut** [orbisgis/geoclimate#864]
Hi!

I open a new ticket concerning an old one (request for feature):
[Add informations on building typologies at RSU scale in UTRF classification (ask for enhancement) #748](https://github.com/orbisgis/geoclimate/issues/748)
for a desired, and potentially usefull, **TYPO_SECOND** attribute which could give us directly what should be the  "Secondary" architectural/urban typology at RSU scale (like in MApUCE data outputs)...

As been told in previous ticket's response, we do actually have the distribution of each building type in each RSU and the UNIQUENESS_VALUE attribute in Geoclimate rsu_utrf outputs,  which is based on this **TYPO_SECOND**  attribute : "The value of the uniqueness main class for the RSU defined as (FRACTION TYPO_MAJ - FRACTION TYPO_SECOND) / (FRACTION TYPO_MAJ + FRACTION TYPO_SECOND)", as confirmed in the UTRF RSU Wiki page.

But the desired **TYPO_SECOND** attribute values are not present in **rsu_utrf_floor_area** and **rsu_utrf_area** output layer files.

Could it be possible to give directly this **TYPO_SECOND** attribute to users, rather than having to use a postprocesssing  of the distribution values?

Thanks by advance.

Serge.

**Comment by j3r3m1** [comment]
Hi @sfaraut,

According to your demand on the previous ticket, we have created a new output from GeoClimate to meet the requirements you had. You left the choice to have either TYPO_MAJ and TYPO_SECOND or having the distribution, we chose to save the distribution since it is the raw data that can then be postprocessed to do whatever you would like (if your need change).

We can make the modification in the code ([here](https://github.com/orbisgis/geoclimate/blob/a811f3321e44b728ff30e8d415eb4366da06c91c/geoindicators/src/main/groovy/org/orbisgis/geoclimate/geoindicators/WorkflowGeoIndicators.groovy#L977)) to also add the TYPO_SECOND but I need validation from @ebocher since it affects the layout of the output tables.
