### ISSUE TITLE
Missing of spatial unity in the Nancy study area

### ISSUE THREAD

**Issue by EmmanuelleKerjouan** [orbisgis/geoclimate#872]
If you look at the results of Geoclimate's output of a study envelope around Nancy, you'll notice a gap. This hole is present in both version 2 and version 3 of the BDTopo. 
Here are the coordinates of the bounding boxe in 2154 : 6836343.6284,924280.9312,6855225.3440,944570.1370
![Capture d’écran du 2023-11-08 16-30-09](https://github.com/orbisgis/geoclimate/assets/126885597/acd59d8e-4b4e-49c0-8819-893d6649f7c4)
![Capture d’écran du 2023-11-08 16-36-02](https://github.com/orbisgis/geoclimate/assets/126885597/e5a12d05-f667-46f3-b09e-66f485be56fe)

**Comment by ebocher** [comment]
Tested with the current master with the bbox  [6842120.833, 926434.890,    6845298.174,930662.645], I'm not able to reproduce the issue.

![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/727cb89a-f8d6-46f9-8931-5da337591102)

Note that the LCZ map shows a higher proportion of LCZ 105. This is due to the vegetation layer which is not sufficiently detailed.


![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/5688d13a-db64-481e-a37c-f3b25478aaca)

**Comment by EmmanuelleKerjouan** [comment]
@j3r3m1 No with the latest version the problem is no longer present.
