### ISSUE TITLE
Sassenage is related to the town hall not to the municipal boundaries

### ISSUE THREAD

**Issue by balglave** [orbisgis/geoclimate#873]
When extracting the data for "Sassenage", I only extract the boundary of the town hall, but I would like the municipal boundaries. Do you know where could be the problem ?

**Comment by j3r3m1** [comment]
I have tested and indeed it does not work properly. Strange because as far as I know, GeoClimate is using the first result of Nominatim which for Sassenage gives the [boundaries of the commune(https://nominatim.openstreetmap.org/ui/search.html?q=Sassenage).

@ebocher an idea ?

Anyway for now you can make the calculation for a bbox instead of a location name (such as for this bbox: http://bboxfinder.com/#45.178467,5.640192,45.224914,5.721474).

See the corresponding tutorial in the wiki.

**Comment by balglave** [comment]
I'll do. Thanks !

**Comment by ebocher** [comment]
It's due to the nominatim output file. The query returns a geojson file with  two polygons : one for the adminsitrative area and the other for the town hall
![geoms](https://github.com/orbisgis/geoclimate/assets/1820572/844aa5c0-7406-4249-8d65-c3445aa8d1e2)

We must filter the polygon with the property type = administrative
