### ISSUE TITLE
Roads/tracks in the countryside

### ISSUE THREAD

**Issue by wurtzj** [orbisgis/geoclimate#887]
Hi everyone,

We are experiencing some strange road fractions in Essone departement (while it seems Ok on Eure et Loire).
Are "track" roads are taking into account in the total road fraction ? If yes, maybe it would be better to include them in the bare soil fraction ? 

Thanks,

Jean

**Comment by ebocher** [comment]
Is it possible to share a bbox  area  or a link from https://www.openstreetmap.org/ ?
Cheers

**Comment by j3r3m1** [comment]
@wurtzj tracks are taken only if they have a surface that belong to one of the following: ['unpaved', 'asphalt', 'paved', 'cobblestone', 'metal', 'concrete', 'compacted'] (cf. https://github.com/orbisgis/geoclimate/blob/870015f18eb224210180e9c8d5f3a8edad473021/osm/src/main/groovy/org/orbisgis/geoclimate/osm/InputDataFormatting.groovy#L330C63-L330C143).

Many tracks do not have a surface type. However they might have a tracktype and in this case we derive the surface from the following rules: https://github.com/orbisgis/geoclimate/blob/870015f18eb224210180e9c8d5f3a8edad473021/osm/src/main/groovy/org/orbisgis/geoclimate/osm/InputDataFormatting.groovy#L294 

As you can see, a track having a grade4 or grade5 as tracktype or having no surface type will not be conserved for any analysis.

This is why it might be interesting if you can give us the zone you meet strange results since it might be explainable by the tracktype or the surface missing.

I had a try for the following bbox: http://bboxfinder.com/#48.236565,1.913681,48.300782,2.032814
It is difficult to say anything about such small zone but visually it seems that the tracks are not taken into account both in the West or in the East of the train line (which is near the department boundary):
![image](https://github.com/orbisgis/geoclimate/assets/13120405/11463791-7fbd-4849-96bf-e4e3ed6273f7)
![image](https://github.com/orbisgis/geoclimate/assets/13120405/8f3ca0f0-85a5-4a43-b2a2-e8e3cd86d34e)

**Comment by j3r3m1** [comment]
I have investigated at larger scale the differences nearby the boundary between the 2 departments (let's say left and right) and I cannot see much difference when averaging results at grid scale.

@wurtzj, is it nearby this zone that you have observed problems ?
![image](https://github.com/orbisgis/geoclimate/assets/13120405/02f86c20-78c8-459d-b5e4-e948ecccc9ba)

**Comment by wurtzj** [comment]
Hi @j3r3m1 

Thanks for having a look. It seems that either this is not an issue, or this issue comes from post-processing.
But  strangefully as looking more closely to the map it seems there are indeed more roads on the left handside department. 
Maybe more money for roads there ?...
