### ISSUE TITLE
Marseille has a problem

### ISSUE THREAD

**Issue by balglave** [orbisgis/geoclimate#943]
It seams Marseille has a problem with geoclimate. When I exrtact the data I get this: 
![image](https://github.com/orbisgis/geoclimate/assets/57452072/c1fc7277-4f42-4b59-818e-97d0c27afd70)

**Comment by j3r3m1** [comment]
Last GeoClimate snapshot ?
Which dataset ? OSM or BDTopo (which version) ?

**Comment by j3r3m1** [comment]
OK I had a try with a SNAPSHOT version from beginning of March, there is indeed a problem with the OSM data. Maybe this problem was raised when the Gascogne issue was solved ?
The corresponding PR is: https://github.com/orbisgis/geoclimate/pull/906
I am testing a GeoClimate version from mid December to check that.

**Comment by ebocher** [comment]
I'm on it

**Comment by ebocher** [comment]
The sea/land mask layer is well engineered for Marseille.

![geoms_pb](https://github.com/orbisgis/geoclimate/assets/1820572/7bf0be14-c31a-43d7-a97d-565cf91be08a)

Investigations are needed in the workflow
