### ISSUE TITLE
Take into account null road type

### ISSUE THREAD

**Issue by ebocher** [orbisgis/geoclimate#99]
When the data is transformed from OSM to Geoclimate model, it's possible to obtain a road type with a null value.
The inputDataFormatting process doesn't check that.

@j3r3m1

**Comment by ebocher** [comment]
The same for building layer

**Comment by gpetit** [comment]
Hi guys.
Ok so the idea would be to add two updates in the inputDataFormating.sql file to take into acount these cases.
We could have something like this
* for BUILDING, when TYPE is null then TYPE='building'
* for ROAD, when TYPE is null then TYPE='highway'

Since the TYPE is also used for vegetation and rail, maybe we should add the same update too? If so, what kind of TYPE should we apply ? Because there is no "generic" term in the abstract table (eg: vegetation, rail ...)

**Comment by gpetit** [comment]
But when I think about it, I don't know if this is the right place. 
In theory, the data (from OSM or BD Topo,...) must conform to the model. And the model says you have to have a TYPE, present in the abstract lists.
If this is not the case, it is because the transformation is not "compliant" and the UPDATE (that I was talking about just before) should be added in the OSM part ?
What do you think ?

**Comment by ebocher** [comment]
Seems correct to fix this null on the osm side. I will do that.
Nevertheless, it would be nice to integrate this as a unit test to ensure the quality of the result after data formatting.

**Comment by gpetit** [comment]
Ok.
I create an issue concerning the list of the unit tests --> #103
